### ISSUE TITLE
Your Recent Packages and Your Common Packages show &#xA;

### ISSUE THREAD

**Issue by davidlsharp1** [praeclarum/FuGetGallery#57]
Under the "Your Recent Packages" and "Your Common Packages" the package details are shown with the line feed code instead of rendering a new line.

![fuget](https://user-images.githubusercontent.com/7958760/52890409-30f1ba80-314a-11e9-94f2-5cd34457a8ca.PNG)

**Comment by bgrainger** [comment]
I pushed a fix for this here: https://github.com/bgrainger/FuGetGallery/commit/59b4c6285b990514206dfb78866f0be56e144f7e

Because the incorrect data (in the generated HTML) is cached aggressively by the browser, then cached in localStorage (for the MRU list) it will require clearing the browser cache and local site data for the fix to be visible (once this is deployed).

**Comment by praeclarum** [comment]
To your point about the caching, it’s my intentions to fix at least the localStorage to be updated more often so fixes/updates will propagate faster.
