### ISSUE TITLE
System.Net.Http doesn't show all TFM

### ISSUE THREAD

**Issue by jeremyVignelles** [praeclarum/FuGetGallery#59]
[This page](https://www.fuget.org/packages/System.Net.Http/4.3.4) shows only net46, while more target frameworks are available for this package, see : https://www.nuget.org/packages/System.Net.Http/4.3.4

**Comment by praeclarum** [comment]
My list only shows frameworks from the libs - that is, code that is shipped in the nuget. It doesn't show dependency TFMs. 

The problem is libraries like System.Net.Http are just placeholders (SDKs contain them) and don't actually include any code for those platforms.

One of the reasons I wrote FuGet was I wanted to know exactly which code a nuget contained and therefore see this shorter list as a feature.

That said, I should do something for these redirect assemblies to make that clearer...

**Comment by loic-sharma** [comment]
@praeclarum Do you also look at the "ref" directories in NuGet packages? A package may support a target framework due to assemblies in the "ref" and "runtime" directories without having anything in the "lib" directory. See: https://docs.microsoft.com/en-us/nuget/create-packages/select-assemblies-referenced-by-projects#packagereference-support
